### ISSUE TITLE
Error on line 571:18:TypeError: null is not an object (evaluating 'number.toString()')

### ISSUE THREAD

**Issue by sfksuperman** [Hider-alt/covid-widget#1]
It's not working now. How to fix?
![image](https://user-images.githubusercontent.com/34414624/192118197-89880304-7e6f-45f8-b362-8460e84f5209.png)

**Comment by Hider-alt** [comment]
Could you tell me what country have you selected?

**Comment by sfksuperman** [comment]
> Could you tell me what country have you selected?

India.
It was working till today. Did you make any changes in Country names? If yes, please do let me know. Thanks.

**Comment by Hider-alt** [comment]
Understood. This is a problem with data processing by the APIs. The widget is expected to work again in the next few hours when the daily death data is released. However this problem will be fixed in the next version (which will be released in the next 2/3 days), as I will change the API.

**Comment by sfksuperman** [comment]
Ok thanks. I will check back in 3 days then.

**Comment by Hider-alt** [comment]
I've released the new version. Let me know if the bug is fixed

**Comment by sfksuperman** [comment]
> I've released the new version. Let me know if the bug is fixed

It's fixed now. Thanks.
